NDefines.NMilitary.UNIT_EXPERIENCE_PER_COMBAT_HOUR = 0.0003
NDefines.NMilitary.EXPERIENCE_LOSS_FACTOR = 0.5
NDefines.NMilitary.BATALION_CHANGED_EXPERIENCE_DROP = 0.25
NDefines.NNavy.UNIT_EXPERIENCE_PER_COMBAT_HOUR = 7.5
